//Home Screen
export const PRODUCT_LIST_REQUEST="PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS="PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL="PRODUCT_LIST_FAIL";

//Product Details
export const PRODUCT_DETAILS_REQUEST="PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS="PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL="PRODUCT_DETAILS_FAIL";

//deleting products
export const PRODUCT_DELETE_FAIL="PRODUCT_DELETE_FAIL";
export const PRODUCT_DELETE_REQUEST="PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS="PRODUCT_DELETE_SUCCESS";

//adding Products
export const PRODUCT_ADDED_REQUEST="PRODUCT_ADDED_REQUEST";
export const PRODUCT_ADDED_SUCCESS="PRODUCT_ADDED_SUCCESS";
export const PRODUCT_ADDED_FAIL="PRODUCT_ADDED_FAIL";

//updating products
export const PRODUCT_UPDATE_REQUEST="PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS="PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL="PRODUCT_UPDATE_FAIL";